### ISSUE TITLE
i cant test this, pls help

### ISSUE THREAD

**Issue by BeshkekArt** [Ryhon0/sbox-gg#1]
After ClientRpc code give that error 
**[ClientRpc] can only be added to static methods or to Entity or EntityComponent types** 
in Game.cs 

I am newbie in this, pls fix this((( i so wanna it
-->
[ClientRpc]
void UpdateWeaponList( string weapons, string name )
{
	RotationName = name;
	Weapons = weapons.Split( ',' ).ToList();
}

public void RequestWeapon( Player p )
{
	GiveWeapon( p, GetWeapon( p.GetClientOwner().GetScore<int>( "rank", 0 ) ) );
}

[ClientCmd( "weapons" )]
public static void ListWeapons()
{
	Log.Info( string.Join( ',', Library.GetAllAttributes<Weapon>().Select( w => w.Name ).Where( w => w != "Weapon" ) ) );
}

**Comment by Ryhon0** [comment]
I haven't updated this project in 2 years, the APIs must've changed and I don't have interest in updating it right now
